Servers/Servers/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Servers.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<ServersModel> Servidores{ get; set; }
    }
}

Servers/Servers/Models/ErrorViewModel.cs
using System;

namespace Servers.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Servers/Servers/Models/ServersModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Servers.Models
{
    public class ServersModel
    {
            [Key]
            public int ServID { get; set; }

            [Required(ErrorMessage = "Ingrese el nombre del servidor")]
            [Display(Name = "Servidor")]
            public string ServName { get; set; }

            [Required(ErrorMessage = "Ingrese nombre del País")]
            [Display(Name = "País")]
            public string ServCountry { get; set; }

            [Required(ErrorMessage = "Ingrese el ping entre 10 y 600")]
            [Display(Name = "Ping promedio")]
            [Range(10, 600)]
            public int AvgMS { get; set; }

            [Required(ErrorMessage = "Ingresa el TAG")]
            [Display(Name = "TAG de País")]
            [StringLength(2)]
            public string Game { get; set; }
    }
    
}

Servers/Servers/Controllers/ServersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Servers.Models;

namespace Servers.Controllers
{
    public class ServersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ServersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Servidores.ToList();
            return View(displaydata);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ServersModel nServ)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nServ);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nServ);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Servidores.FindAsync(id);
            return View(getEmpDdetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Servidores.FindAsync(id);
            return View(getEmpDdetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ServersModel oldEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldEmp);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDdetail = await _db.Servidores.FindAsync(id);
            return View(getEmpDdetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getEmpDdetail = await _db.Servidores.FindAsync(id);
            _db.Servidores.Remove(getEmpDdetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Servers/Servers/Views/Servers/Create.cshtml
@model Servers.Models.ServersModel

@{
    ViewData["Title"] = "Create";
}

<h1>Añadir Servidor</h1>

<h4>Servidores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ServName" class="control-label"></label>
                <input asp-for="ServName" class="form-control" />
                <span asp-validation-for="ServName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServCountry" class="control-label"></label>
                <input asp-for="ServCountry" class="form-control" />
                <span asp-validation-for="ServCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvgMS" class="control-label"></label>
                <input asp-for="AvgMS" class="form-control" />
                <span asp-validation-for="AvgMS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Game" class="control-label"></label>
                <input asp-for="Game" class="form-control" />
                <span asp-validation-for="Game" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Añadir" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Servers/Servers/Views/Servers/Delete.cshtml
@model Servers.Models.ServersModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Servidor</h1>

<h3>¿Estas seguro de borrar el servidor?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvgMS)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvgMS) ms
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Game)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Voler a la lista</a>
    </form>
</div>

Servers/Servers/Views/Servers/Detail.cshtml
@model Servers.Models.ServersModel

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del Servidor</h1>

<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvgMS)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvgMS) ms
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Game)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ServID }) |
    <a asp-action="Index">Volver a la lista</a>
</div>

Servers/Servers/Views/Servers/Edit.cshtml
@model Servers.Models.ServersModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Servidor</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServID" class="control-label"></label>
                <input asp-for="ServID" class="form-control" readonly/>
                <span asp-validation-for="ServID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServName" class="control-label"></label>
                <input asp-for="ServName" class="form-control" />
                <span asp-validation-for="ServName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServCountry" class="control-label"></label>
                <input asp-for="ServCountry" class="form-control" />
                <span asp-validation-for="ServCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvgMS" class="control-label"></label>
                <input asp-for="AvgMS" class="form-control" />
                <span asp-validation-for="AvgMS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Game" class="control-label"></label>
                <input asp-for="Game" class="form-control" />
                <span asp-validation-for="Game" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Servers/Servers/Views/Servers/Index.cshtml
@model IEnumerable<Servers.Models.ServersModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Servidores</h1>

<p>
    <a asp-action="Create">Añadir Servidor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ServID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvgMS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Game)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvgMS) ms
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Game)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.ServID }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.ServID }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.ServID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Servers/Servers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Servers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Servers" asp-action="Index">Servers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Servers" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Servers 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>